<?php

require('model/elements/Element.php');
require('model/elements/Image.php');
require('model/elements/Video.php');
require('model/elements/Table.php');
require('model/elements/Navbar.php');
require('model/elements/Title.php');
require('model/elements/Footer.php');
require('model/elements/Text.php');
require('model/elements/Background.php');
require('model/elements/Code.php');
require('model/elements/Facebook.php');
require('model/layouts/Layout.php');
require('model/layouts/LayoutMain.php');
require('model/layouts/LayoutAside.php');
require('model/layouts/LayoutBottom.php');
require('model/layouts/LayoutHeader.php');
require('model/layouts/LayoutFooter.php');